[renderer]
height = 720
vsync = true
width = 1280

[settings]
debug = true
use_experimental_customization = false

[style]
background-color = [ 0.06, 0.05, 0.07, 1.0 ]
border-color = [ 0.8, 0.8, 0.83, 0.88 ]
border-shadow-color = [ 0.92, 0.91, 0.88, 0.0 ]
button-active-color = [ 0.56, 0.56, 0.58, 1.0 ]
button-color = [ 0.1, 0.09, 0.12, 1.0 ]
button-hovered-color = [ 0.24, 0.23, 0.29, 1.0 ]
checkmark-color = [ 0.8, 0.8, 0.83, 0.31 ]
font-family = 'segoeuib.ttf'
font-size = 19
frame-active-background-color = [ 0.56, 0.56, 0.58, 1.0 ]
frame-background-color = [ 0.1, 0.09, 0.12, 1.0 ]
frame-hovered-background-color = [ 0.24, 0.23, 0.29, 1.0 ]
frame-padding = [ 5, 5 ]
frame-rounding = 4.0
grab-min-size = 5.0
grab-rounding = 3.0
header-active-color = [ 0.06, 0.05, 0.07, 1.0 ]
header-color = [ 0.1, 0.09, 0.12, 1.0 ]
header-hovered-color = [ 0.56, 0.56, 0.58, 1.0 ]
indent-spacing = 25.0
item-inner-spacing = [ 8, 6 ]
item-spacing = [ 12, 8 ]
menu-bar-background-color = [ 0.1, 0.09, 0.12, 1.0 ]
popup-background-color = [ 0.07, 0.07, 0.09, 1.0 ]
scrollbar-background-color = [ 0.1, 0.09, 0.12, 1.0 ]
scrollbar-grab-active = [ 0.06, 0.05, 0.07, 1.0 ]
scrollbar-grab-color = [ 0.8, 0.8, 0.83, 0.31 ]
scrollbar-grab-hovered = [ 0.56, 0.56, 0.58, 1.0 ]
scrollbar-rounding = 9.0
scrollbar-size = 15.0
slider-grab-active-color = [ 0.06, 0.05, 0.07, 1.0 ]
slider-grab-color = [ 0.8, 0.8, 0.83, 0.31 ]
text-color = [ 0.8, 0.8, 0.83, 1.0 ]
text-disabled-color = [ 0.24, 0.23, 0.29, 1.0 ]
text-selected-background-color = [ 0.25, 1.0, 0.0, 0.43 ]
title-active-background-color = [ 0.07, 0.07, 0.09, 1.0 ]
title-background-color = [ 0.1, 0.09, 0.12, 1.0 ]
title-collapsed-color = [ 1.0, 0.98, 0.95, 0.75 ]
window-padding = [ 15, 15 ]
window-rounding = 5.0